[keyboard]
bindings = [
    { action = "ToggleFullscreen", key = "F11" },
]

[bell]
color = "#ffffff"

[font]
size = 14.0

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[colors.primary]
background = "#300A24"
foreground = "#FFFFFF"

[colors.normal]
black = "#2E3436"
red = "#CC0000"
green = "#4E9A06"
yellow = "#C4A000"
blue = "#3465A4"
magenta = "#75507B"
cyan = "#06989A"
white = "#D3D7CF"

[colors.bright]
black = "#555753"
red = "#EF2929"
green = "#8AE234"
yellow = "#FCE94F"
blue = "#729FCF"
magenta = "#AD7FA8"
cyan = "#34E2E2"
white = "#EEEEEC"
